name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.2'

      - name: Build
        run: |
          export GOOS="linux darwin windows"
          export GOARCH="amd64"
          for GOOS in $GOOS; do
              for GOARCH in $GOARCH; do
                  export GOOS GOARCH
                  go build -o app-${GOOS}-${GOARCH} main.go
              done
          done
